BASE <http://yago-knowledge.org/resource/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX kb: <http://yago-knowledge.org/resource/>
SELECT ?X WHERE { 
	{ ?X kb:wasBornIn []. } 
	UNION 
	{ ?X kb:wasBornOnDate []. }

	MINUS
	{ ?X kb:diedIn []. } 
	MINUS
	{ ?X kb:diedOnDate []. }
}




